name: CI/CD for Azure Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Log in to Azure CLI
      run: az login

    - name: Copy Index File
      run: cp .github/workflows/index.html $GITHUB_WORKSPACE

    - name: Deploy to Azure Functions
      run: |
        npm install -g azure-functions-core-tools
        func azure functionapp publish az400-87361891-func1 --force
