name: Azure Function App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'  # Adjust the version as needed

    - name: Build with dotnet
      run: dotnet build MyFunctionApp.csproj --configuration Release

    - name: Publish Artifact
      run: dotnet publish MyFunctionApp.csproj -c Release -o $(Build.ArtifactStagingDirectory)

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'az400-87361891-func1'
        package: $(Build.ArtifactStagingDirectory)
